
name: Create '~/.aws/credentials' file Action for GitHub Actions
description: Creates '~/.aws/credentials' file for use in subsequent steps in a GitHub Action workflow
runs:
  using: node20
  main: dist/index.js
  post: dist/cleanup/index.js
inputs:
  profile:
    description: AWS profile name to use in the credentials file.
    required: true
  aws-region:
    description: AWS Region, e.g. us-east-2
    required: true
  aws-access-key-id:
    description: AWS Access Key ID.
    required: true
  aws-secret-access-key:
    description: AWS Secret Access Key.
    required: true
